SET VERIFY OFF
connect "SYS"/"&&sysPassword" as SYSDBA
set echo on
spool /home/oracle/app/oracle/admin/Lifintsev/scripts/CreateDBFiles.log append
CREATE SMALLFILE TABLESPACE "KIRI" LOGGING DATAFILE '/home/oracle/app/oracle/oradata/Lifintsev/kiri.dbf' SIZE 10M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;
CREATE SMALLFILE TABLESPACE "USERS" LOGGING DATAFILE '/home/oracle/app/oracle/oradata/Lifintsev/users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;
ALTER DATABASE DEFAULT TABLESPACE "USERS";
spool off
